### ISSUE TITLE
Authentication issue when Security token not set

### ISSUE THREAD

**Issue by farbel** [dataiku/dss-plugin-salesforce#6]
There are situations where security token may not be needed to be set to authenticate (e.g. using relaxed IP restrictions), in these cases authentication data sent to Salesforce is malformed ('_None_' appended to the password field)

**Comment by alexbourret** [comment]
This issue should be fixed in [v1.2.1](https://github.com/dataiku/dss-plugin-salesforce/releases/tag/v1.2.1)
